### PR TITLE
A couple of test suites for partial cubes

### PR DESCRIPTION
**Pull request by vrajat**

### CODE REVIEW

**Comment by vrajat** [comment]
I will add one more for tiered cubes tests. Started PR as a preview.

**Comment by amoghmargoor** [comment]
These are fantastic tests. 
I think we had discussed to allow only conjunctions in the filter, but implementation can handle any arbitary complex expression with any nesting of AND, OR operator. We can have one such test with such complex expression. Looking at tests I think there is one case where implementation might break down, which is for user queries with operator 'in'. if 'in operator doesnot get expanded internally by calcite then following test would break:
cube query : d_year = 2007 and d_moy in (1,2,3,4,5)
user query : d_year = 2007 and d_moy in (3,4)

**Comment by vrajat** [comment]
Interesting case. I'll add it.

**Comment by vrajat** [comment]
I added `day2and3FilterMatch`. It passed.

**Comment by vrajat** [comment]
I'll need help in analyzing the failures. In my previous commit, I created a new suite called `LayeredCube`. It has 3 cubes at daily, weekly and monthly granularity for different months of the year. Then ran queries and expect them to choose a valid cube or not. QUeries are only picking up daily cube when applicable. Its quite possible there are setup problems too.

**Pull request closed without merging**
